/** Region / language codes → display labels (shared by rankings API + Guild). */

const REGION_NAMES: Record<string, string> = {
  en: 'English',
  ru: 'Russia',
  uk: 'Ukraine',
  uz: 'Uzbekistan',
  tr: 'Turkey',
  de: 'Germany',
  fr: 'France',
  es: 'Spain',
  it: 'Italy',
  pt: 'Portugal',
  ar: 'Arabic',
  zh: 'China',
  ja: 'Japan',
  ko: 'Korea',
  id: 'Indonesia',
  hi: 'India',
  bn: 'Bangladesh',
  vi: 'Vietnam',
  th: 'Thailand',
  ms: 'Malaysia',
  pl: 'Poland',
  nl: 'Netherlands',
  fa: 'Iran',
  he: 'Israel',
  cs: 'Czech Republic',
  ro: 'Romania',
  hu: 'Hungary',
  el: 'Greece',
  sv: 'Sweden',
  da: 'Denmark',
  fi: 'Finland',
  no: 'Norway',
  be: 'Belarus',
  kk: 'Kazakhstan',
  az: 'Azerbaijan',
  ka: 'Georgia',
  hy: 'Armenia',
  sr: 'Serbia',
  hr: 'Croatia',
  bg: 'Bulgaria',
  sk: 'Slovakia',
  sl: 'Slovenia',
  lt: 'Lithuania',
  lv: 'Latvia',
  et: 'Estonia',
  tg: 'Tajikistan',
  ky: 'Kyrgyzstan',
  tk: 'Turkmenistan',
  mn: 'Mongolia',
  my: 'Myanmar',
  ne: 'Nepal',
  si: 'Sri Lanka',
  km: 'Cambodia',
  lo: 'Laos',
  fil: 'Philippines',
  am: 'Ethiopia',
  sw: 'Swahili / East Africa',
  af: 'South Africa',
  zu: 'Zulu',
};

export function getRegionDisplayName(code: string | null | undefined): string {
  if (code == null || code === '') return 'Unspecified';
  const key = code.toLowerCase();
  if (key === 'unknown') return 'Unknown';
  return REGION_NAMES[key] || code.toUpperCase();
}
