'use client';

import React from 'react';
import Link from 'next/link';
import { triggerHapticFeedback } from '@/utils/ui';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#1d2025] text-white">
      <div className="sticky top-0 z-10 bg-[#1d2025] border-b border-[#3d4046] px-4 py-3 flex items-center justify-between">
        <h1 className="text-lg font-bold text-[#f3ba2f]">Privacy Policy</h1>
        <Link
          href="/clicker"
          onClick={() => triggerHapticFeedback(window)}
          className="text-sm text-[#f3ba2f] font-medium"
        >
          Back to app
        </Link>
      </div>
      <div className="px-4 py-6 pb-24 max-w-xl mx-auto prose prose-invert prose-sm">
        <p className="text-gray-400 text-xs mb-4">Last updated: February 2025</p>

        <h2 className="text-white font-semibold mt-6 mb-2">1. Introduction</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          URAPearls (&quot;we&quot;, &quot;our&quot;, or &quot;the app&quot;) is a Telegram Mini App that lets you earn in-app points (PEARLS), complete tasks, refer friends, and use features such as staking and mini-games. This Privacy Policy explains how we collect, use, and protect your information when you use URAPearls.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">2. Information We Collect</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-2">
          We receive and store information that Telegram provides when you open the app, including:
        </p>
        <ul className="list-disc pl-5 text-gray-300 text-sm space-y-1 mb-4">
          <li>Your Telegram user ID and username</li>
          <li>Your first and last name (if shared with the bot)</li>
          <li>Init data from Telegram for authentication</li>
        </ul>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We also store data generated by your use of the app: in-app points (PEARLS), balance, level, energy, upgrades, completed tasks, referral links, staking records, and similar game progress. If you connect a TON wallet (e.g. for Lumina ID or airdrops), we may store wallet address and related data necessary to provide those features.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">3. How We Use Your Information</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We use your information to: operate the app (e.g. sync progress, process taps, tasks, and referrals); calculate and display levels, rewards, and leaderboards; send you in-app notifications and, if you have connected our bot, messages to your Telegram chat; prevent abuse and enforce our Terms of Service; and improve the app and user experience.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">4. Sharing of Information</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We do not sell your personal data. We may share data with service providers that help us run the app (e.g. hosting, databases). If we use Telegram channels or bots to send announcements, your Telegram ID may be used to deliver those messages. We may disclose information if required by law or to protect our rights and safety.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">5. Data Retention</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We retain your account and game data for as long as your account is active and as needed to provide the service, resolve disputes, and comply with legal obligations.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">6. Security</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We use industry-standard measures to protect your data. Authentication is performed using Telegram&apos;s init data. No passwords are stored by us for the Mini App.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">7. Your Rights</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          Depending on your jurisdiction, you may have the right to access, correct, or delete your personal data. Contact us through the official URAPearls Telegram channel or bot support to make a request.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">8. Children</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          URAPearls is not directed at children under 13 (or the applicable age in your country). We do not knowingly collect data from such users.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">9. Changes</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          We may update this Privacy Policy from time to time. Continued use of the app after changes constitutes acceptance. We encourage you to review this page periodically.
        </p>

        <h2 className="text-white font-semibold mt-6 mb-2">10. Contact</h2>
        <p className="text-gray-300 text-sm leading-relaxed mb-4">
          For questions about this Privacy Policy or your data, contact us via the official URAPearls Telegram channel or support contact provided in the app.
        </p>
      </div>
    </div>
  );
}
